'126898852241473537':
  Enabled: true
  Offset: '-4:0'
  Secretary: ''
  Shipfu: Graf Zeppelin
'138149441335984133':
  Enabled: false
  Offset: '-4:0'
  Secretary: https://cdn.discordapp.com/attachments/293504101738610690/306641057540603904/2327f47746bbe368d5c516e84eeb0609.jpg
  Shipfu: Haruna
'141366245399330816':
  Enabled: true
  Offset: '-4:0'
  Secretary: ''
  Shipfu: Commandant Teste
'187262611295961089':
  Enabled: true
  Offset: 4:-1
  Secretary: ''
  Shipfu: Akitsu Maru
'194178693113839618':
  Enabled: true
  Offset: '2:0'
  Secretary: ''
  Shipfu: Graf Zeppelin
'196194242836561920':
  Enabled: true
  Offset: '3:0'
  Secretary: ''
  Shipfu: Kongou
'198433755671691264':
  Enabled: true
  Offset: '2:0'
  Secretary: https://cdn.discordapp.com/attachments/285537911414325249/290168501212020736/eyJ1cmwiOiJodHRwczovL3NhZmVib29ydS5vcmcvaW1hZ2VzLzE5NDQvODZmMzY1ZWViYmMwZGVjNzQxZTc3OWYyY2FjZGU5N2Q0Nzk4ZTg0My5qcGcifQ.jpg
  Shipfu: Yamato
'233425999986032640':
  Enabled: true
  Offset: '14:0'
  Secretary: ''
  Shipfu: Saratoga
'273163799492689931':
  Enabled: true
  Offset: '-5:0'
  Secretary: ''
  Shipfu: Bismarck
'283354535857225731':
  Enabled: false
  Offset: '-4:0'
  Secretary: ''
  Shipfu: Taihou
'98201428434104320':
  Enabled: false
  Offset: '20:0'
  Secretary: https://vignette2.wikia.nocookie.net/kancolle/images/1/15/BB_Nagato_Kai_Ni_541_Full.png/revision/latest?cb=20170522114932
  Shipfu: Nagato
