---
  Graf Zeppelin:
    - Am I to depart? That would be good, yes?
    - What is it - you seem to be concerned. The flight decks are continually being maintained by myself. There is no need to worry.
    - What is the meaning of this? This is not the style of your fleet, is it? An explanation, if you'd please.
    - Messerschmitt… that has a good airframe. The Focke-Wulf is an extremely strong fighter, too… Ja. This fleet's airframes also... A…Admiral is also quite good. N-No, it's nothing.
    - Admiral? Is there something on your mind? I see. That's fine then... If you wish to consult on commerce raiding then... No, if there is anything at all, it's fine to talk to me about it first.