'126898852241473537':
  Enabled: true
  Offset: '-4:0'
  Secretary: https://danbooru.donmai.us/data/__graf_zeppelin_kantai_collection_drawn_by_karo_chan__fcb7369f4b570df6771143a4972a960e.png
  Shipfu: Graf Zeppelin
'141366245399330816':
  Enabled: true
  Offset: '-4:0'
  Secretary: ''
  Shipfu: Commandant Teste
'177272994400305153':
  Enabled: true
  Offset: '-4:0'
  Secretary: https://worldofwarships-na.gcdn.co/dcont/fb/image/de16eeae-2cef-11e6-9c02-d89d6715223c.jpg
  Shipfu: Haruna
'194178693113839618':
  Enabled: true
  Offset: '1:0'
  Secretary: https://k60.kn3.net/0/3/4/0/2/E/F44.png
  Shipfu: Graf Zeppelin
'198433755671691264':
  Enabled: true
  Offset: '1:0'
  Secretary: https://cdn.discordapp.com/attachments/285537911414325249/290168501212020736/eyJ1cmwiOiJodHRwczovL3NhZmVib29ydS5vcmcvaW1hZ2VzLzE5NDQvODZmMzY1ZWViYmMwZGVjNzQxZTc3OWYyY2FjZGU5N2Q0Nzk4ZTg0My5qcGcifQ.jpg
  Shipfu: Yamato
'98201428434104320':
  Enabled: true
  Offset: '-4:0'
  Secretary: https://pbs.twimg.com/media/CODSVZBXAAAQiUV.jpg:large
  Shipfu: Musashi
